plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4.8
  TargetRailsVersion: 8.0.2.1

  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "Gemfile"
    - "vendor/**/*"
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false
  
Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "**/spec/**/*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 60
  Exclude:
    - "**/*_spec.rb"
    - "spec/factories/*.rb"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
